### ISSUE TITLE
Why two Ecmascript standards and indentation style are being mixed?

### ISSUE THREAD

**Issue by momozor** [beCoditive/Becoditive-API#13]
Hi. 

Sorry for addressing this, but I think it's better for it to be now than down the road later. :cry: 

1. I've seen plenty of `async()` over `async function f()` and in other part of the code, `function()` vs `() => {.. }`  being used.
Is there any particular reason why the codebase is using both ES5 and ES6 syntax? I understand, they are valid to use in
the same codebase, it's just, I don't see any reasonable benefits to include both style. By the way, if the codebase sticks with ES6, I'm sure it can be compiled to ES5 through `babel` or similar to ensure backward compatibility with old browsers, if that is the primary reason with the mix.

2. Indentation styling, as far as I can see, is not practiced consistently either. 
Sometimes, there are uses of semicolon, sometimes not. Plenty of incosistent `function(){` vs `function() {`, etc.
I see that the code style aligns closely with https://standardjs.com/rules.html, is that correct? If yes, `standard` package can be
used to automatically format the whole codebase format style to follow that `standardjs`' standard.

Thanks for reading. :3

**Comment by Max2408** [comment]
I understand the the 2 problem and it will be fixed soon.

As for the first issue the ES5 syntax is only used for local functions which are not to be exported to the client side and ES6 is used for the all controllers, so i don't see the point in making it also in ES6.

Thanks for opening the issue all the points which are nectary will be fixed soon..

**Comment by Max2408** [comment]
I understand the the 2 problem and it will be fixed soon.

As for the first issue the ES5 syntax is only used for local functions which are not to be exported to the client side and ES6 is used for the all controllers, so i don't see the point in making it also in ES6.

Thanks for opening the issue all the points which are nectary will be fixed soon..

**Comment by momozor** [comment]
Also, is there any reason why some files are named using *Uppercase.js* and some others *lowercase.js*?

**Comment by Max2408** [comment]
NO that is  a mistake I will fix it with camel casing.

**Comment by momozor** [comment]
Ah. Gotcha.
