### ISSUE TITLE
Problem With Package.json

### ISSUE THREAD

**Issue by Max2408** [beCoditive/Becoditive-API#15]
@momozor  The package-lock.json you added in the repo as some vulnerabilities please fix the file and add the file back.

**Comment by momozor** [comment]
Ah. It's great that the bot picked up the vulnerability issue in the dependencies. I'm working on it.

**Comment by momozor** [comment]
@Max2408 Apparently, this project is depending on [swig](https://www.npmjs.com/package/swig), which was abandoned last 7 years ago? It isn't possible to fix the vulnerability (uglify-js and minimist) without removing this swig package. Do you use swig for anything? (I suspect, it's templating stuff).

**Comment by Max2408** [comment]
let me see just a second

**Comment by Max2408** [comment]
swig isn't used now! in v2 i removed all the use of it but forgot to remove it from pacakge.json

**Comment by Max2408** [comment]
thanks !

**Comment by momozor** [comment]
> thanks !

:3 no problem
